### docker build -t fedimoss/kt-sglang:v0.5.18 -f docker/Dockerfile-fedimoss .

### 多线程加载模型
### --model-loader-extra-config '{"enable_multithread_load":true,"num_threads":2}'


### watch -n 2 "numactl --hardware | grep -E 'node|free'"   #查看NUMA node 内存分配
### numactl --interleave=all ##轮询分配, 均匀使用所有节点的内存


# 使用 NVIDIA CUDA 13.0.3 + cuDNN 开发镜像作为基础
FROM nvidia/cuda:13.0.3-cudnn-devel-ubuntu22.04

# 解决 apt 安装时的交互式弹窗 (如时区选择) 
ENV DEBIAN_FRONTEND=noninteractive

## 禁用sglang的自动绑定NUMA
ENV SGLANG_NUMA_BIND_V2=0
ENV SGLANG_AUTO_NUMA_BIND=0

# 【关键】针对 ARM64 架构换源 (替换 ports.ubuntu.com) 
RUN sed -i 's/ports.ubuntu.com/mirrors.tuna.tsinghua.edu.cn\/ubuntu-ports/g' /etc/apt/sources.list


# 1. 更新 apt 并安装必要的工具
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    numactl \
    git \
    ca-certificates \
    software-properties-common \
    && rm -rf /var/lib/apt/lists/*

# 2. 添加 deadsnakes PPA (提供最新 Python 版本的第三方仓库) 
RUN add-apt-repository ppa:deadsnakes/ppa -y && \
    sed -i 's/ppa.launchpad.net/mirrors.tuna.tsinghua.edu.cn\/ubuntu-ppa/g' /etc/apt/sources.list.d/*.list && \
    apt-get update

# 3. 安装 Python 3.12 及其开发工具
RUN apt-get install -y --no-install-recommends \
    python3.12 \
    python3.12-dev \
    python3.12-venv \
    && rm -rf /var/lib/apt/lists/*

# 4. 安装 pip (使用官方 bootstrap 脚本, 确保与 Python 3.12 完美匹配) 
RUN wget https://bootstrap.pypa.io/get-pip.py \
    && python3.12 get-pip.py \
    && rm get-pip.py

# 5. 设置软链接, 让 python / python3 / pip 默认指向 Python 3.12
RUN ln -sf /usr/bin/python3.12 /usr/local/bin/python \
    && ln -sf /usr/bin/python3.12 /usr/local/bin/python3 \
    && ln -sf /usr/local/bin/pip3 /usr/local/bin/pip

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

#  (可选) 验证安装
RUN python --version && pip --version

# 恢复交互式环境变量 (可选) 
ENV DEBIAN_FRONTEND=

# 设置工作目录
WORKDIR /workspace


# 安装Rust (使用国内镜像和非交互模式) 
ENV RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup
ENV RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"


### git clone https://github.com/springrain/ktransformers.git
### git submodule update --init --force --recursive

# 复制 ktransformers 文件夹到 /workspace/
#COPY ktransformers /workspace/ktransformers

COPY ./ /workspace/ktransformers


# 如果 install.sh 在里面, 给执行权限并运行
RUN chmod +x /workspace/ktransformers/install.sh && \
    bash /workspace/ktransformers/install.sh

# 默认进入 bash
CMD ["/bin/bash"]
