### docker build -t fedimoss/kt-sglang:v0.5.19 -f docker/Dockerfile-fedimoss .

### 多线程加载模型
### --model-loader-extra-config '{"enable_multithread_load":true,"num_threads":2}'

### `--kt-method LLAMAFILE` 目前未实现支持 `--kt-gpu-prefill-token-threshold` 和 `--kt-enable-dynamic-expert-update`. 可以使用 `--kt-method MXFP4`

### watch -n 2 "numactl --hardware | grep -E 'node|free'"   #查看NUMA node 内存分配
### numactl --interleave=all ##轮询分配, 均匀使用所有节点的内存


# 使用 NVIDIA CUDA 13.0.3 + cuDNN 开发镜像作为基础
FROM nvidia/cuda:13.0.3-cudnn-devel-ubuntu24.04

# 解决 apt 安装时的交互式弹窗 (如时区选择) 
ENV DEBIAN_FRONTEND=noninteractive

## 禁用sglang的自动绑定NUMA
ENV SGLANG_NUMA_BIND_V2=0
ENV SGLANG_AUTO_NUMA_BIND=0

## 使用UTF-8编码
ENV LANG=C.UTF-8 \
    LC_ALL=C.UTF-8 \
    PYTHONIOENCODING=utf-8

# 针对 ARM64 架构换源 (替换 ports.ubuntu.com) 
#RUN sed -i 's/ports.ubuntu.com/mirrors.tuna.tsinghua.edu.cn\/ubuntu-ports/g' /etc/apt/sources.list
RUN sed -i 's@http://ports.ubuntu.com/ubuntu-ports@https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/@g' /etc/apt/sources.list.d/ubuntu.sources

# 1. 安装 Python 3.12 及其开发工具
RUN apt-get update && apt-get install -y --no-install-recommends \
    wget \
    curl \
    numactl \
    git \
    ffmpeg \
    ca-certificates \
    software-properties-common \
    python3.12 \
    python3.12-venv \
    python3.12-dev \
    python3-pip \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# 2. 设置软链接, 让 python / python3 / pip 默认指向 Python 3.12
RUN ln -sf /usr/bin/python3.12 /usr/local/bin/python \
    && ln -sf /usr/bin/python3.12 /usr/local/bin/python3 \
    && ln -sf /usr/local/bin/pip3 /usr/local/bin/pip


# 3. 创建虚拟环境并设为默认
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

#  (可选) 验证安装
RUN python --version && pip --version

# 恢复交互式环境变量 (可选) 
ENV DEBIAN_FRONTEND=

# 设置工作目录
WORKDIR /workspace


# 安装Rust (使用国内镜像和非交互模式) 
ENV RUSTUP_DIST_SERVER=https://mirrors.tuna.tsinghua.edu.cn/rustup
ENV RUSTUP_UPDATE_ROOT=https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
ENV PATH="/root/.cargo/bin:${PATH}"


### git clone https://github.com/springrain/ktransformers.git
### git submodule update --init --force --recursive

# 复制 ktransformers 文件夹到 /workspace/
#COPY ktransformers /workspace/ktransformers

COPY ./ /workspace/ktransformers


# 如果 install.sh 在里面, 给执行权限并运行
RUN chmod +x /workspace/ktransformers/install.sh && \
    bash /workspace/ktransformers/install.sh

# 默认进入 bash
CMD ["/bin/bash"]
